
#Apply via: ansible-playbook -i ./stack_inventory.yaml --become 05_docker-dtr_deploy.yaml

#---------------------------------------------------------------

# - name: Copy and Import Docker Images 
#   hosts: stack
#   tasks:
#     - name: "Copy docker image export (*.tar) to target hosts"
#       copy:
#         src: "{{docker_img_src}}/"
#         dest: "{{upload_target}}/docker_images"
    
#     - name: Import docker image from upladed src
#       shell: "docker load < {{upload_target}}/docker_images/{{item['file']}}"
#       loop: "{{docker_stack_images}}"

#-----------------------------------------

- name: Check if DTR is already deployed 
  hosts: swarm_init
  gather_facts: no
  tasks:
  - shell: "docker ps -a | grep dtr"
    register: dtr_chk_str
    #ignore_errors: yes
    #no_log: True
    failed_when: "'error message' in dtr_chk_str.stderr"
  - debug:
      msg: "{{hostvars[swarm_init]['dtr_chk_str'].stdout | length}}"
  - debug:
      msg: 'DTR is already deployed on stack'
    when: "hostvars[swarm_init]['dtr_chk_str'].stdout | length > 0"

- name: Deploy Docker DTR on Stack 
  hosts: swarm_init
  vars_prompt:
  - name: ucp_admin
    prompt: "Enter UCP admin user name"
    private: no
    default: admin
  - name: ucp_pwd
    prompt: "Enter UCP admin password"
    private: yes
 
  vars:
    dtr_run_command: "{{ lookup('template', './conf_templates/dtr_run.command') }}"

  tasks:
    - meta: end_play
      when: "hostvars[swarm_init]['dtr_chk_str'].stdout | length > 0"
    - debug: "msg={{dtr_run_command}}"
    - name: "Initialite DTR Containers"
      shell: "{{dtr_run_command}}"
      #register: result
    
#---------------------------------------------------------------