#Apply via: ansible-playbook -i ./deploy_ssh_inventory.yaml --become --ask-become-pass deploy_ssh_playbook.yaml

#---------------------------------------------------------------
- name: "Deploy ssh public key to target hosts"
  gather_facts: yes
  hosts: all
  tasks:
  - name: "Create ssh target user"
    user:
      name: "{{target_usr}}"
      group: wheel
      state: present
      #state: absent
      #remove: yes

  - name: "Add publich key in target users authorized keys" 
    authorized_key:
      user: "{{target_usr}}"
      state: present
      #state: absent
      key: "{{ lookup('file', target_pub_key) }}"
