
#Apply via: ansible-playbook -i ./inventory.yaml --become stack_base_config.yaml

#---------------------------------------------------------------

- name: General OS Config 
  hosts: stack
  tasks:
    - name: Set Timezone
      command: timedatectl set-timezone Europe/Berlin

    #- name: upgrade all packages
    #  yum: name=* state=latest

    - name: Create hosts file from J2 Template
      template:
        src: ./conf_templates/hosts.template
        dest: /etc/hosts

    - name: Disallow ssh password authentication
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication no"
        state=present

    - name: Restart ssh server
      service: 
        name: sshd
        state: restarted
  
#---------------------------------------------------------------
