
#Apply via: ansible-playbook -i ./inventory.yaml --become stack_reset.yaml

#---------------------------------------------------------------

- name: Reset Stack Config 
  hosts: stack
  vars_prompt:
    - name: swarm_reset
      prompt: "Reset docker swarm? (yes/no)"
      private: no
    - name: docker_reset
      prompt: "Uninstall docker? (yes/no)"
      private: no
  
  tasks:
    - name: Gather the package facts
      package_facts:
        manager: auto
    - block:
      - name: "Check if Swarm is initialized"
        shell: docker info | grep "Swarm"
        register: result
      
      - name: "Delete all services"
        shell: docker service rm $(docker service ls -q)
        when: "'inactive' not in result.stdout and swarm_reset == 'yes' and inventory_hostname == swarm_init"

      - name: "Destroy swarm config "
        shell: docker swarm leave --force
        when: "'inactive' not in result.stdout and swarm_reset == 'yes'"

      - name: Un-Install docker ee 
        yum: 
          name: "{{item}}"
          state: absent
          autoremove: yes
        loop: "{{docker_ee_pkgs}}"
        when: docker_reset == 'yes'
      
      when: "'docker-ee' in ansible_facts.packages"
 
  
#---------------------------------------------------------------
